const products = [{
        '_id': '1',
        'name': 'Mango Cake',
        'image': '/images/mango.jpeg',
        'description': 'Decription Here',
        'brand': 'Bakers',
        'category': 'Cake',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Unicorn Cake',
        'image': '/images/unicorn.jpeg',
        'description': 'Decription Here',
        'brand': 'Bakers',
        'category': 'Cake',
        'price': 599.99,
        'countInStock': 0,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Fruit Cake',
        'image': '/images/fruit.jpeg',
        'description': 'Decription Here',
        'brand': 'Bakers',
        'category': 'Cake',
        'price': 929.99,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'BlackForest Cake',
        'image': '/images/blackforest.jpeg',
        'description': 'Decription Here',
        'brand': 'Bakers',
        'category': 'Cake',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Doll Cake',
        'image': '/images/doll.jpeg',
        'description': 'Decription Here',
        'brand': 'Bakers',
        'category': 'Cake',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Chocolacious Cake',
        'image': '/images/chococake.jpeg',
        'description': 'Decription Here',
        'brand': 'Bakers',
        'category': 'Cake',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
]


export default products